# Configuration file for the Kangaroo robot
ankle_ft_left:
  description: "Force-torque sensor on the left ankle"
  choices: ["no-ft-sensor", "ati"]
  default_value: "no-ft-sensor"

ankle_ft_right:
  description: "Force-torque sensor on the right ankle"
  choices: ["no-ft-sensor", "ati"]
  default_value: "no-ft-sensor"

end_effector_right:
  description: "choose the desired end effector right with its corresponding arm."
  choices: ["no-end-effector", "gripper", "RH8D"]
  default_value: "no-end-effector"

end_effector_left:
  description: "choose the desired end effector left with its corresponding arm."
  choices: ["no-end-effector", "gripper", "RH8D"]
  default_value: "no-end-effector"

fixation_type:
  description: "Fixation type"
  choices: ["crane", "fixed", "floating"]
  default_value: "floating"

ft_sensor_right:
  description: "Force-torque sensor on the right arm"
  choices: ["no-ft-sensor", "ati"]
  default_value: "no-ft-sensor"

ft_sensor_left:
  description: "Force-torque sensor on the left arm"
  choices: ["no-ft-sensor", "ati"]
  default_value: "no-ft-sensor"

feet_type:
  description: "Adds legs to the model"
  choices: ["fixed", "detachable"]
  default_value: "fixed"

arm_type:
  description: "Adds arms to the model"
  choices: ["no-arm", "4dof", "5dof", "7dof"]
  default_value: "4dof"

has_pelvis:
  description: "Adds the 2 DoFs of the pelvis to the model"
  choices: ["True", "False"]
  default_value: "True"

has_head:
  description: "Adds a head of 2 DoFs to the model"
  choices: ["True", "False"]
  default_value: "False"

collision_type:
  description: "Type of collision geometry"
  default_value: "mesh"
  choices: ["mesh", "capsule"]

sim_type:
  description: "Simulation type"
  default_value: "no-simulation"
  choices: ["mujoco-ros2-control", "mujoco", "no-simulation"]

use_mimic:
  description: "Whether to include the mimic joints in the model"
  choices: ["True", "False"]
  default_value: "False"

torso_imu_model:
  description: "Type of IMU for the torso"
  choices: ["orientus", "microstrain", "no-imu"]
  default_value: "orientus"

base_imu_model:
  description: "Type of IMU for the base"
  choices: ["microstrain", "no-imu"]
  default_value: "no-imu"