${LEG_SIDE_PREFIX}_position_${INTERFACE_LEVEL}_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    open_loop_control: true
    joints:
      - ${LEG_SIDE_PREFIX}_1_${INTERFACE_LEVEL}
      - ${LEG_SIDE_PREFIX}_2_${INTERFACE_LEVEL}
      - ${LEG_SIDE_PREFIX}_3_${INTERFACE_LEVEL}
      - ${LEG_SIDE_PREFIX}_length_${INTERFACE_LEVEL}
      - ${LEG_SIDE_PREFIX}_4_${INTERFACE_LEVEL}
      - ${LEG_SIDE_PREFIX}_5_${INTERFACE_LEVEL}
    command_interfaces:
      - position
    state_interfaces:
      - position

    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 5.0
      ${LEG_SIDE_PREFIX}_1_joint:
        goal: 0.02
      ${LEG_SIDE_PREFIX}_2_joint:
        goal: 0.02
      ${LEG_SIDE_PREFIX}_3_joint:
        goal: 0.02
      ${LEG_SIDE_PREFIX}_4_joint:
        goal: 0.02
      ${LEG_SIDE_PREFIX}_5_joint:
        goal: 0.02
      ${LEG_SIDE_PREFIX}_length_joint:
        goal: 0.001

