#!/usr/bin/env python3

# Copyright (c) 2024 PAL Robotics S.L. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os

import sys

import em

em_file_path = sys.argv[1]

no_em_extension_path = os.path.splitext(em_file_path)[0]
no_extension_path = os.path.splitext(no_em_extension_path)[0]
extension = os.path.splitext(no_em_extension_path)[1]

# Pairs [arm_type, end_effector_type]
valid_pairs = [['4dof', 'no-end-effector'], ['5dof', 'RH8D'], ['5dof', 'no-end-effector'],
               ['7dof', 'gripper'], ['7dof', 'no-end-effector'], ['no-arm', 'no-end-effector']]

for has_pelvis in [True, False]:
    for arm_type, end_effector in valid_pairs:
        cfg = {
            'has_arms': arm_type != 'no-arm',
            'arm_type': arm_type,
            'end_effector': end_effector,
            'has_pelvis': has_pelvis
        }

        with open(em_file_path, 'r') as f:
            expanded_contents = em.expand(f.read(), cfg)

        suffix = (
            '_' + f'{arm_type}_' + f'{end_effector}' + '_'
            + f'{"with-pelvis" if has_pelvis else "no-pelvis"}'
        )

        expanded_file_name = no_extension_path + suffix + extension
        with open(expanded_file_name, 'w') as f:
            msg = "Autogenerated file, don't edit this, edit {} instead".format(
                os.path.basename(em_file_path))
            if extension == '.yaml':
                f.write('#' + msg + '\n')
            elif extension in ['.xacro', '.xml', '.srdf']:
                f.write('<!-- ' + msg + '-->\n')

            f.write(expanded_contents)
